# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Library.create({name: 'Tareek', git_url: 'https://github.com/gemathon-warriors/tareek', classification: 'Date&Time'})
Library.create({name: 'Timezonify', git_url: 'https://github.com/gemathon-warriors/timezonify', classification: 'Date&Time'})
Library.create({name: 'spicon', git_url: 'https://github.com/gemathon-warriors/spicon', classification: 'CSS'})
Library.create({name: 'contineo', git_url: 'https://github.com/gemathon-warriors/contineo', classification: 'Database'})
Library.create({name: 'strolljs-rails', git_url: "https://github.com/gemathon-warriors/strolljs-rails", classification: 'Javascript'})
Library.create({name: 'week_calc', git_url: "https://github.com/Gemathon-Chargers/week_calc", classification: 'Date&Time'})
Library.create({name: 'password_mate', git_url: "https://github.com/Gemathon-Chargers/password_mate", classification: 'Ruby'})
Library.create({name: 'objectify_params', git_url: "https://github.com/Gemathon-Chargers/objectify_params", classification: 'Ruby'})
Library.create({name: 'sliced_bread', git_url: "https://github.com/Gemathon-Chargers/sliced_bread", classification: 'Ruby'})
Library.create({name: 'whiteorblack-rails', git_url: "https://github.com/gemathon-rockets/whiteorblack", classification: 'Javascript'})
Library.create({name: 'encrypter_decrypter_files', git_url: "https://github.com/gemathon-rockets/encrypter_decrypter_files", classification: 'Crypto'})
Library.create({name: 'tcs-handles-aggregator', git_url: "https://github.com/gemathon-rockets/tcs-handles-aggregator", classification: 'Ruby'})
Library.create({name: 'text_to_color-rails', git_url: "https://github.com/gemathon-rockets/text_to_color-rails", classification: 'Javascript'})
Library.create({name: 'visualsearch-rails', git_url: "https://github.com/gemathon-rockets/visualsearch-rails", classification: 'Javascript'})
Library.create({name: 'scrollreveal-rails', git_url: "https://github.com/gemathon-rockets/scrollreveal-rails", classification: 'Javascript'})
Library.create({name: 'activerecord_html_stripper', git_url: "https://github.com/gemathon-rockets/activerecord_html_stripper", classification: 'Ruby'})
Library.create({name: 'button_helper', git_url: "https://github.com/Gemathon-Lapidarists/button_helper", classification: 'Ruby'})
Library.create({name: 'distance_in_weeks', git_url: "https://github.com/Gemathon-Lapidarists/distance_in_weeks", classification: 'Date&Time'})
Library.create({name: 'group_records', git_url: "https://github.com/Gemathon-Lapidarists/group_records", classification: 'Database'})
Library.create({name: 'array_zipper', git_url: "https://github.com/Gemathon-Lapidarists/array_zipper", classification: 'Ruby'})
Library.create({name: 'multi_sort', git_url: "https://github.com/Gemathon-Lapidarists/multi_sort", classification: 'Ruby'})
Library.create({name: 'fork_ribs', git_url: "https://github.com/vipulchhabra/fork_ribs", classification: 'CSS'})
Library.create({name: 'string-surgeon', git_url: "https://github.com/himaenshu/string-surgeon", classification: 'Ruby'})
Library.create({name: 'nested_column_sorting', git_url: "https://github.com/Gemophiliacs/Nested_Column_Sorting", classification: 'Ruby'})
Library.create({name: 'excel_checker', git_url: "https://github.com/GemBursters/excel_checker", classification: 'Ruby'})
Library.create({name: 'logme', git_url: "https://github.com/GemBursters/logme", classification: 'Ruby'})
Library.create({name: 'specialcharacterchecker', git_url: "https://github.com/GemBursters/specialcharacterchecker", classification: 'Ruby'})
Library.create({name: 'github-contributions', git_url: "https://github.com/Manik-Ratnas/github-contributions", classification: 'Ruby'})
Library.create({name: 'scent', git_url: "https://github.com/pythonicrubyist/scent", classification: 'Ruby'})
Library.create({name: 'junkyard', git_url: "https://github.com/pythonicrubyist/junkyard", classification: 'Ruby'})
Library.create({name: 'xlsx2json', git_url: "https://github.com/pythonicrubyist/xlsx2json", classification: 'Ruby'})
Library.create({name: 'set_time_zone', git_url: "https://github.com/Manik-Ratnas/set_time_zone", classification: 'Ruby'})
Library.create({name: 'special_char_remover', git_url: "https://github.com/Manik-Ratnas/special_char_remover", classification: 'Ruby'})
Library.create({name: 'string_matchables', git_url: "https://github.com/Manik-Ratnas/string_matchables", classification: 'Ruby'})
Library.create({name: 'city_detail', git_url: "https://github.com/Manik-Ratnas/city_detail", classification: 'Ruby'})
Library.create({name: 'update_or_create', git_url: "https://github.com/Manik-Ratnas/update_or_create", classification: 'Ruby'})
Library.create({name: 'clean_associations', git_url: "https://github.com/Manik-Ratnas/clean_associations", classification: 'Ruby'})
Library.create({name: 'star_ratings', git_url: "https://github.com/Manik-Ratnas/star_ratings", classification: 'Ruby'})
Library.create({name: 'ar_report', git_url: "https://github.com/Manik-Ratnas/ar_report", classification: 'Ruby'})
Library.create({name: 'gemathon', git_url: "https://github.com/Manik-Ratnas/gemathon", classification: 'Ruby'})
